### ISSUE TITLE
The Google Drive link for the checkpoint is not available

### ISSUE THREAD

**Issue by Xposeder** [hellochick/PSPNet_tensorflow#69]
The Google Drive link for the checkpoint is not available, please provide a new link.

**Comment by hellochick** [comment]
Thank you for pointing out, 
currently I only have the link to the PSPNet (ResNet 50) trained on ADE20K dataset,
Please check: [google drive](https://drive.google.com/drive/folders/1BR9Fq3f9t_NrANfH24Fz3Atoi-HKmp6t?usp=drive_link)

**Comment by Xposeder** [comment]
> Thank you for pointing out, currently I only have the link to the PSPNet (ResNet 50) trained on ADE20K dataset, Please check: [google drive](https://drive.google.com/drive/folders/1BR9Fq3f9t_NrANfH24Fz3Atoi-HKmp6t?usp=drive_link)

Thank you, this works perfectly!
